### ISSUE TITLE
Example script for computing  n-novelty?

### ISSUE THREAD

**Issue by ivnle** [viking-sudo-rm/rusty-dawg#149]
This looks like a very promising project! Thanks for making it available.

Is there an example script to compute the n-novelty for some document  wrt to a corpus (as done in the paper)? I've been able to construct and load the CDAWG of the corpus, but I'm still trying to figure out how to use it to compute n-novelty.

**Comment by viking-sudo-rm** [comment]
Glad to hear you've found the CDAWG useful!

I've actually split a lot of the experimental code for the paper in a [separate repo ](https://github.com/viking-sudo-rm/ngram-copying) which uses Rusty-DAWG as a dependency (I should update the paper to make this clear).

Specifically, you can compute n-novelty from the output of Rusty-DAWG in the `get_proportion_unique` using the method [here](https://github.com/viking-sudo-rm/ngram-copying/blob/main/src/ngram_novelty.py). The method expects a list of lists of suffix lengths (returned by Rusty-DAWG), and gives back two arrays: an array of n-gram sizes, and an array of corresponding novelty values in [0, 1] for each size.
